controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

post_save:
    path: /post/save
    controller: App\Controller\PostController::savePost
    methods: [POST]