doctrine:
    dbal:
        url: 'pgsql://postgres:postgres@localhost:5432/Folklore'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true